In [1]:
import numpy as np
import scipy.linalg as la


In [20]:
A=np.array([[1,2,3],[2,2,2],[3,2,3]])
x0=np.array([1,0,0]).reshape(-1,1)
Ak=np.linalg.matrix_power(A,10)
xk=Ak@x0
# print(xk)
# print((xk/np.linalg.norm(xk)))

valores,vectores=np.linalg.eig(A)
# print(valores)
v1=vectores[:,0]
aux=v1/np.linalg.norm(v1)
# print(aux)


[[0.52774786]
 [0.50489605]
 [0.68305357]]
[0.52774779 0.50489607 0.6830536 ]


In [56]:
A=np.random.randint(1,10,size=[4,4])
At=A.transpose()

valoresA,vectoresA=np.linalg.eig(A)
valoresAt,vectoresAt=np.linalg.eig(At)
print(valoresA)
print(valoresAt)
print(np.poly(valoresA))
# print(vectoresA)
# print(vectoresAt)

[20.17942403 -3.19261095  3.45327435  3.55991258]
[20.17942403 -3.19261095  3.55991258  3.45327435]
[   1.  -24.   67.  243. -792.]


In [59]:
lista = [31.8, 31.9, 32, 32.1, 32.2]
for a in lista:
    A = np.array([[-6, 28, 21],[4, -15, -12],[-8, a, 25]])
    evalues,evectors=np.linalg.eig(A)
    print(np.poly(evalues))


[ 3.12788206 -0.12788206  1.        ]
[ 1.  -4.   2.6  0.4]
[2.70415946 0.29584054 1.        ]
[ 1.  -4.   3.8 -0.8]
[2. 1. 1.]
[ 1. -4.  5. -2.]
[1.5+0.97467943j 1.5-0.97467943j 1. +0.j        ]
[ 1.  -4.   6.2 -3.2]
[1.5+1.46628783j 1.5-1.46628783j 1. +0.j        ]
[ 1.  -4.   7.4 -4.4]


In [62]:
k=17
A=np.array([[1,2,3],[2,2,2],[3,2,3]])
Aj=np.copy(A)
while k>0:
    Q,R=np.linalg.qr(Aj)
    Aj=R@Q
    k-=1
print(Aj.diagonal())
valores,vectores=np.linalg.eig(A)
print(valores)

[ 6.79624015 -1.26244658  0.46620643]
